Ajusta acessibilidade da página inicial
DadosAbertosDeFeira/maria-quiteria pull request #217
Opened 2020-10-04 20:08 UTC by MarcusAldrey

Alterações de tamanhos, cores e tags para melhoria de acessibilidade.
Os elementos alterados foram baseados na análise da ferramenta Lighthouse.

![image](https://user-images.githubusercontent.com/17774194/95025933-e517c000-0663-11eb-810a-39ee50618619.png)

2020-10-04 20:26 UTC, matheusrocha89 requested changes
Deixei alguns comentários para correção, de resto tudo ok

2020-10-04 20:26 UTC, matheusrocha89 commented on home/templates/home/index.html
> +                    <!-- <a class="content href="https://pt.wikipedia.org/wiki/Feira_de_Santana" target="_blank" rel="noopener noreferrer"></a> -->
Se o item não vai ser mais um link melhor deletar do que deixar comentado, assim o código fica mais limpo, pode remover esses códigos comentados 😉

2020-10-04 20:26 UTC, matheusrocha89 commented on home/templates/home/index.html
> +            color: rgb(41, 92, 173) !important;
Nunca use !important isso deixa o código mais difícil de se manter, o melhor é criar uma classe e usar onde você precisa. 👍

Melhor mover isso para uma classe e remover o !important

Já que vamos ter CSS nosso na página, será que já não seria hora de criar nosso arquivo CSS? O que acha @anapaulagomes ?

2020-10-04 21:17 UTC, anapaulagomes commented on home/templates/home/index.html
> +            color: rgb(41, 92, 173) !important;
Sim, acho que é uma boa prática manter os estilos em um arquivo CSS separado. 👍🏽

2020-10-05 23:52 UTC, MarcusAldrey commented on home/templates/home/index.html
> +                    <!-- <a class="content href="https://pt.wikipedia.org/wiki/Feira_de_Santana" target="_blank" rel="noopener noreferrer"></a> -->
Fiz as correções

2020-10-06 07:22 UTC, matheusrocha89 approved these changes
👍

2020-10-08 08:17 UTC, anapaulagomes requested changes
Falta pouco agora. Só precisa mover o arquivo `style.css` para a pasta de arquivos estáticos (não precisa mudar mais nada além disso). 👍🏽

2020-10-08 08:17 UTC, anapaulagomes commented on home/templates/home/style.css
> +.footer-link {
Esse arquivo deve ficar junto com os outros arquivos estáticos em `home/static/home`.

2020-10-08 08:36 UTC, matheusrocha89 commented on home/templates/home/style.css
> +.footer-link {
Putz, me passei no review, esqueci de ver onde o arquivo foi criado 😄 

Mas sim, eu concordo, deve-se mover para a pasta static 👍 

De resto, tudo OK.

2020-10-08 15:48 UTC, MarcusAldrey commented on home/templates/home/style.css
> +.footer-link {
Feito, mas agora o auto check do Github indica erro 

![image](https://user-images.githubusercontent.com/17774194/95482412-776ddb80-0964-11eb-938a-bbefe9df99c4.png)

2020-10-08 16:08 UTC, anapaulagomes commented
A versão do setup foi atualizada (https://github.com/DadosAbertosDeFeira/maria-quiteria/commit/90d2723e4c9c0fb9968ff9f64db5ecff2316a95e). Pode atualizar sua branch, porfa? 🙏🏽

2020-10-08 20:00 UTC, MarcusAldrey commented
Feito

2020-10-09 07:51 UTC, anapaulagomes approved these changes
Excelente! Obrigada, @MarcusAldrey! 🎉

2020-10-09 07:51 UTC, merged