Adição de autenticação JWT para a api
DadosAbertosDeFeira/maria-quiteria pull request #272
Opened 2020-12-31 23:38 UTC by soslaio

Adiciona autenticação via JWT, conforme issue #270. A autenticação é feita através da seguinte requisição:
```
curl -i -H "Content-Type: application/json" -X POST -d '{ "username": "nome_do_usuario", "password": "senha_do_usuario" }' http://localhost:8000/api/token/
```
A resposta deve ser algo parecido com isso:
```
{
    "refresh": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTU4NTA4NzkyMSwianRpIjoiNGYzYWYyNTdlMmMzNDM4OGJjZjQ1ZWM1NDc2M2E2NmIiLCJ1c2VyX2lkIjoxfQ.Qq2k7C9etrqzCgHy2yWTNFZC6TBOeUvsCX6f3A0akQY",
    "access": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjA5NDMzNjg3LCJqdGkiOiJlMmIzYmY3MDNlMGE0Nzg4YTkxMWEzMjYxMzBlNjViNyIsInVzZXJfaWQiOjF9.CwKYEl1jLKGHx_lmrSBxE7TgrePUBexlbjwLG9Ptbs0"
}
```
Utilize o valor retornado em `access` como cabeçalho de autenticação na próxima requisição, como no exemplo abaixo:
```
curl -i -H "Content-Type: application/json" -H "Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjA5NDMzNjg3LCJqdGkiOiJlMmIzYmY3MDNlMGE0Nzg4YTkxMWEzMjYxMzBlNjViNyIsInVzZXJfaWQiOjF9.CwKYEl1jLKGHx_lmrSBxE7TgrePUBexlbjwLG9Ptbs0" http://localhost:8000/api/
```
Por padrão todas as rotas criadas na API só poderão ser acessadas com autenticação, apenas o healthcheck tem acesso público.

Foram disponibilizadas variáveis de ambiente para setar o tempo de vida dos tokens. São elas:

* ACCESS_TOKEN_LIFETIME_IN_MINUTES
* REFRESH_TOKEN_LIFETIME_IN_MINUTES

2021-01-02 07:59 UTC, anapaulagomes requested changes
@soslaio muito obrigada pela contribuição! Tô muito empolgada. 🏆
Testei aqui e funcionou lindo. Deixei algumas sugestões de melhorias. Quando o CI estiver verde, darei uma olhada novamente.

2021-01-02 07:59 UTC, anapaulagomes commented on core/settings.py
> +        os.getenv('ACCESS_TOKEN_LIFETIME_IN_MINUTES', 1440)
Pode colocar um comentário indicando que seriam 24 horas?

```suggestion
        os.getenv('ACCESS_TOKEN_LIFETIME_IN_MINUTES', 1440)  # 24 horas
```

2021-01-02 07:59 UTC, anapaulagomes commented on core/settings.py
> +        os.getenv('REFRESH_TOKEN_LIFETIME_IN_MINUTES', 1440)
O mesmo aqui :)

2021-01-02 07:59 UTC, anapaulagomes commented on core/urls.py
> +    path('api/token/verify/', TokenVerifyView.as_view(), name='token_verify')
O CI está falhando por causa do Black (usamos o padrão da biblioteca - aspas duplas, nesse caso). Pra ajudar com próximos commits, você pode configurar o `pre-commit`. Basta rodar um `pre-commit install` no repositório do projeto.

2021-01-02 07:59 UTC, anapaulagomes commented on api/tests/test_health_check.py
> +
Podemos apagar essa linha extra aqui.

2021-01-02 07:59 UTC, anapaulagomes commented on api/tests/test_health_check.py
> +    def test_return_success_when_accessing_a_restricted_route_with_credentials(
```suggestion
    def test_return_success_when_accessing_non_restricted_route_with_credentials(
```

2021-01-02 07:59 UTC, anapaulagomes commented on api/tests/test_health_check.py
> +    def test_return_forbiden_when_trying_to_anonymously_access_a_restricted_route(
```suggestion
    def test_return_forbidden_when_trying_to_anonymously_access_a_restricted_route(
```

2021-01-02 07:59 UTC, anapaulagomes commented on api/tests/test_health_check.py
> +    def test_return_forbiden_when_trying_to_anonymously_access_a_restricted_route(
Pode adicionar um `#TODO` pra gente remover esse teste pra quando tivermos um endpoint autenticável? O teste é no endpoint de health check mas não pertence a ele. 😅

2021-01-02 07:59 UTC, anapaulagomes commented on api/tests/conftest.py
> +
Podemos apagar essa linha extra aqui.

2021-01-03 21:06 UTC, soslaio commented on api/tests/test_health_check.py
> +    def test_return_success_when_accessing_a_restricted_route_with_credentials(
Acho que o nome que você sugeriu não reflete o que o teste faz.

2021-01-03 21:08 UTC, soslaio commented
@anapaulagomes obrigado pelas sugestões, só ficou 1 pendente.

2021-01-04 08:02 UTC, anapaulagomes approved these changes
Wohooo! Valeu @soslaio! 🎉

2021-01-04 08:02 UTC, anapaulagomes commented on api/tests/test_health_check.py
> +    def test_return_success_when_accessing_a_restricted_route_with_credentials(
Verdade! Agora que olhei novamente vi que não faz sentido. 👍🏽

2021-01-04 08:02 UTC, merged

2021-01-04 08:13 UTC, anapaulagomes commented
Aproveitei os exemplos do teu PR pra adicionar uma documentação na nossa [wiki](https://github.com/DadosAbertosDeFeira/maria-quiteria/wiki/API).