Adiciona endpoint para CityCouncilAgenda
DadosAbertosDeFeira/maria-quiteria pull request #277
Opened 2021-01-06 19:53 UTC by beatrizuezu

- Adiciona endpoint para CityCouncilAgenda, com filtros `query`, `start_date` e `end_date`.
 
 Issue https://github.com/DadosAbertosDeFeira/maria-quiteria/issues/246

2021-01-06 21:16 UTC, anapaulagomes requested changes
Obrigada pela contribuição, @beatrizuezu! :) Muito legal ver um código tão limpo e funcionando bem. Testei local e tudo certo! Deixei poucos comentários para melhorias. Assim que estivermos pronto, podemos mergear. 🎉

2021-01-07 00:53 UTC, beatrizuezu commented on api/tests/test_views.py
> +        data = response.json()[0]
nao sei se entendi muito bem, seria outro teste ou um outro assert verificando o tamanho da lista?

2021-01-07 01:01 UTC, beatrizuezu commented on api/tests/test_views.py
> +                "Deve ser no formato  YYY-MM-DD."
achei estranho que o `exc.value.message` tá retornando `"Deve ser no formato  YYY-MM-DD."`.


![Screenshot from 2021-01-06 21-42-52](https://user-images.githubusercontent.com/5013052/103837450-1be9e180-506a-11eb-8839-904cd67d15d5.png)

![Screenshot from 2021-01-06 21-35-11](https://user-images.githubusercontent.com/5013052/103837497-1f7d6880-506a-11eb-8be7-570009b7854f.png)


Achei que fosse alguma coisa de traduação, e olhando nas traduções do django tá errado mesmo[1]

[1] https://github.com/django/django/blob/5fcfe5361e5b8c9738b1ee4c1e9a6f293a7dda40/django/conf/locale/pt_BR/LC_MESSAGES/django.po#L528

2021-01-07 09:49 UTC, anapaulagomes commented on api/tests/test_views.py
> +        data = response.json()[0]
Realmente eu não expliquei direito 😅 seria bom ter mais um objeto e depois verificar o tamanho da lista (além dos asserts que tu já está fazendo).

2021-01-07 09:51 UTC, anapaulagomes commented on api/tests/test_views.py
> +                "Deve ser no formato  YYY-MM-DD."
![](https://media.giphy.com/media/3kzJvEciJa94SMW3hN/giphy.gif)

E aí, vai abrir esse PR lá? ;) (podemos deixar assim então - quando for corrigido o teste vai quebrar e a gente conserta)

2021-01-07 13:17 UTC, beatrizuezu commented on api/tests/test_views.py
> +                "Deve ser no formato  YYY-MM-DD."
vou abrir sim!

2021-01-07 13:45 UTC, anapaulagomes approved these changes
Nosso primeiro endpoint retornando dados! Wohooo! 🎉 Obrigada, @beatrizuezu!

2021-01-07 13:46 UTC, merged