Endpoint para diários oficiais (#227)
DadosAbertosDeFeira/maria-quiteria pull request #286
Opened 2021-01-25 01:35 UTC by soslaio

Adiciona o endpoint para diários oficiais com opções de filtros via interface browseable do django rest framework.

A rota adicionada foi `api/gazettes`. Os filtros são feitos através que query string, e são eles:

- `search`: procura a palavra dentro do diários e dos eventos do diário
- `power`: filtra os diários pelo poder (executivo ou legislativo)
- `start`: filtra os diários que tenham a data maior ou igual à data especificada
- `end`: filtra os diários que tenham a data menor ou igual à data especificada

Os filtros podem ser combinados entre eles.

2021-01-25 16:33 UTC, anapaulagomes requested changes
Obrigada por mais uma contribuição, @soslaio! 🎉 Muito legal esses filtros na interface da API.
Precisamos mudar os nomes, apenas. Também faltou retornar a URL do arquivo do diário (que está em `files__url`, salvo engano) que é diferente do `crawled_from`. Assim as pessoas poderão acessar ao PDF diretamente.

2021-01-25 16:33 UTC, anapaulagomes commented on web/api/filters.py
> +        fields = ["power", "start", "end"]
Massa, hein?

2021-01-25 16:33 UTC, anapaulagomes commented on web/api/views.py
> +        "files__content",
Aqui temos que usar o campo do full-text search (`search_vector`), se não a busca fica super lenta.

2021-01-25 16:33 UTC, anapaulagomes commented on web/api/views.py
> +from rest_framework.filters import SearchFilter
Podemos mudar o nome para `query` ao invés de `search`? Os outros endpoints já adotaram essa convenção: `query`, `start_date`, `end_date`. Seria bom mantê-los.

2021-01-25 16:33 UTC, anapaulagomes commented on web/api/tests/test_views.py
> +            ({"start": "2021-01-02", "end": "2021-03-15"}, 1),
Poderia adicionar um teste para todos os campos juntos?

2021-01-25 20:16 UTC, soslaio commented on web/api/filters.py
> +        fields = ["power", "start", "end"]
Né? achei essas features integradas bem legais.

2021-01-25 20:16 UTC, soslaio commented on web/api/views.py
> +        "files__content",
Boa! já é!

2021-01-25 20:17 UTC, soslaio commented on web/api/views.py
> +from rest_framework.filters import SearchFilter
Ajustado.

2021-01-25 20:17 UTC, soslaio commented on web/api/tests/test_views.py
> +            ({"start": "2021-01-02", "end": "2021-03-15"}, 1),
Boa lembrança. Adicionei.

2021-01-25 20:22 UTC, soslaio commented
Acho que já foram todos os ajustes.

2021-01-29 14:27 UTC, anapaulagomes commented on web/api/views.py
> +        "files__search_vector",
Creio que assim não funciona. Acabei de testar aqui e um termo simples como "merenda" não é encontrado. Como a forma de realizar buscas com [_full-text search_](https://docs.djangoproject.com/en/3.1/ref/contrib/postgres/search/) é diferente, talvez aqui precise de alguma adaptação também.

2021-01-29 14:32 UTC, anapaulagomes commented on web/api/views.py
> +        "files__search_vector",
Para `start_date` também não. Estou usando _query parameters_ para fazer as consultas.

Ao usar a interface e pesquisar por "valor" no Pesquisar, a busca está bem lenta (+40s). Me pergunto se devemos fazer algo por aqui ou alguma outra modificação (estamos com o mesmo problema no #284 cc @joorgelm).

2021-02-20 07:52 UTC, anapaulagomes commented on web/api/views.py
> +        "files__search_vector",
Opa! Precisando de alguma ajuda por aqui @soslaio?

2021-02-20 14:59 UTC, soslaio commented on web/api/views.py
> +        "files__search_vector",
Opa @anapaulagomes passei uns 20 dias viajando, agora que voltei pra casa, aí vou retomar essa issue.

2021-07-06 19:59 UTC, anapaulagomes commented
Olá, @soslaio! Consegue dar uma força pra gente nesse PR? Estamos começando o desenvolvimento do bot do diário oficial e vamos precisar desse endpoint.
Se não der, pode me avisar? 🙏🏽

2021-07-06 20:08 UTC, soslaio commented
Oi @anapaulagomes. Pelo que lembro esbarrei nesse PR em questões de banco que não domino muito, e atualmente ando sem tempo pra investigar essa questão mais a fundo. Se alguém puder continuar de onde parei ou fazer um novo, seria melhor pra não atrapalhar o andamento do projeto.

2021-07-06 20:10 UTC, anapaulagomes commented
Tranquilo! Obrigada 😌 @soslaio

2021-07-07 14:27 UTC, closed without merging