Instalado e Configurado o NewRelic
DadosAbertosDeFeira/maria-quiteria pull request #306
Opened 2021-03-26 00:39 UTC by Riverfount

Relativo à issue de número 45 do repositório iac.

2021-03-26 05:35 UTC, anapaulagomes commented on web/settings.py
> +    NEW_RELIC_CONFIG_FILE = os.getenv("NEW_RELIC_CONFIG_FILE", "newrelic.ini")
Tem alguma chance de termos arquivos de configuração diferentes para o new relic?

2021-03-27 13:55 UTC, gomex commented on web/settings.py
> +    NEW_RELIC_CONFIG_FILE = os.getenv("NEW_RELIC_CONFIG_FILE", "newrelic.ini")
@anapaulagomes você diz um arquivo novo tipo web/newrelic_settings.py ?

2021-03-27 13:58 UTC, anapaulagomes commented on web/settings.py
> +    NEW_RELIC_CONFIG_FILE = os.getenv("NEW_RELIC_CONFIG_FILE", "newrelic.ini")
Não, de ter um outro que não seja `newrelic.ini`. Se não, a minha sugestão seria deixar o valor hardcoded mesmo.

```suggestion
    NEW_RELIC_CONFIG_FILE = "newrelic.ini"
```

2021-03-27 13:59 UTC, anapaulagomes commented on web/settings.py
> +    ENABLE_NEW_RELIC = False
Essa pode ficar em `Common`, daí é herdada por todas as outras até ser sobrescrita (como em Prod).

2021-03-27 14:02 UTC, gomex requested changes
Precisamos trabalhar no preenchimento do newrelic.ini. Podemos colocar ele na raiz do repo sem os dados sensíveis e trocar isso no CI/CD.

Pensei bastante aqui sobre o teste, mas não acho que tenha forma fácil de fazer, sendo assim eu ficarei satisfeito se isso estiver rodando ok no fork, apontando para outra conta com outra APIKEY. Quero ver isso rodando na  newrelic no fork.

2021-03-27 14:02 UTC, gomex commented on web/settings.py
> +    NEW_RELIC_CONFIG_FILE = os.getenv("NEW_RELIC_CONFIG_FILE", "newrelic.ini")
Não acho que tenha mesmo, mas sempre gosto de oferecer a opção de mudança de parâmetros, se vc prefere o nome hardcoded, eu estou ok com isso ;)

2021-03-27 14:04 UTC, anapaulagomes commented on web/settings.py
> +    NEW_RELIC_CONFIG_FILE = os.getenv("NEW_RELIC_CONFIG_FILE", "newrelic.ini")
Deixamos como está então :)

2021-03-27 14:11 UTC, gomex commented
Esse PR está relacionada a essa issue: https://github.com/DadosAbertosDeFeira/iac/issues/45

2021-03-27 17:17 UTC, Riverfount commented on web/settings.py
> +    ENABLE_NEW_RELIC = False
Ok, como é um jeito diferente do que estou acostumado de gerenciar os ambientes fiquei na dúvida mesmo! Vou alterar isso no PR!

2021-03-27 17:23 UTC, Riverfount commented on web/settings.py
> +    NEW_RELIC_CONFIG_FILE = os.getenv("NEW_RELIC_CONFIG_FILE", "newrelic.ini")
IMHO pelo que entendi da documentação do NewRelic sim, eu posso dar outro nome ao arquivo newrelic.ini, por isso eu defino qual é o arquivo pela variável de ambiente `NEW_RELIC_CONFIG_FILE`, pois se não fosse isso não vejo muito sentido ser necessário definir a variável de ambiente antes de executar o serviço do newrelic. Faz sentido isso para vocês?

2021-04-03 18:52 UTC, gomex requested changes

2021-04-03 18:52 UTC, gomex commented on newrelic.ini
> +app_name = vm_mariaquiteria (Staging)
Trocar pra um nome mais genérico.

2021-04-03 18:52 UTC, gomex commented on web/settings.py
> +    NEW_RELIC_APP_NAME = os.getenv("NEW_RELIC_APP_NAME", "vm_mariaquiteria")
Trocar pra um nome mais genérico.

2021-08-09 18:41 UTC, anapaulagomes commented
Olá, galera. Como estamos com essa issue aqui?

2021-08-13 20:30 UTC, gomex commented
@anapaulagomes eu vou buscar alguém que tenha conhecimento em python pra tocar isso, ok?

2021-09-12 04:03 UTC, exageraldo commented
@gomex o que falta para finalizarmos essa tarefa? Aplicar as melhorias sugeridas no review? Vi que já saiu uma nova versão da biblioteca, acho que podemos atualizar.

2021-09-13 03:12 UTC, gomex commented
> @gomex o que falta para finalizarmos essa tarefa? Aplicar as melhorias sugeridas no review? Vi que já saiu uma nova versão da biblioteca, acho que podemos atualizar.

Eu acho uma boa sim. Está afim de trabalhar nisso?

2021-09-13 10:41 UTC, exageraldo commented
Opa, estou sim!

2021-09-13 11:07 UTC, exageraldo commented
Sobre um nome mais generico para o `app_name`, cê acha que algo como `web_app` tá bom? Como é staging, nós devemos colocar algo como `web_app_stag`?

Sobre os comentários/documentação no arquivo `newrelic.ini`, cês acham que é de boas deixar lá, ou deixamos apenas as configs mesmo? Se formos deixar, acham que vale a pena traduzir?

2021-09-13 13:32 UTC, snifbr commented
Bom dia @gomex e @exageraldo, estava em andamento com essa configuração do NewRelic para python-app. Na verdade já configurei localmente e está funcionando conforme segue meu fork do maria-quiteria, só falta alinhar com o deploy no Dokku.

https://github.com/snifbr/maria-quiteria/commit/209848d07a5cfd1f6e52af4f5a614c5886b96923

Caso @exageraldo puder me ajudar com o entendimento com o Dokku, podemos fazer isso em conjunto, gostaria muito de poder continuar com essa issue DadosAbertosdeFeira/iac#45 ou poder acompanhar para aprender.

2021-09-13 14:03 UTC, exageraldo commented
opa, perfeito @snifbr ! podemos procurar um horário pra parearmos e conversar sobre essa tarefa e dokku. o que acha?

2021-09-13 14:16 UTC, snifbr commented
Claro @exageraldo pode me adicionar/procurar no discord rocha#5418

2021-09-16 00:36 UTC, snifbr commented on newrelic.ini
> +app_name = vm_mariaquiteria (Staging)
@gomex em conversa com @exageraldo decidimos retirar essas declarações de sections de Environments por achar desnecessário, só utilizariamos a variável de ambiente `NEW_RELIC_APP_NAME` no `.env`.

2021-09-16 00:39 UTC, snifbr commented on web/settings.py
> +    NEW_RELIC_APP_NAME = os.getenv("NEW_RELIC_APP_NAME", "vm_mariaquiteria")
@gomex , eu e o @exageraldo mudamos a linha 174 para `os.getenv("NEW_RELIC_APP_NAME", None)`, deixando a cargo da variável de ambiente `NEW_RELIC_APP_NAME` no `.env` setar o nome da aplicação para o NewRelic.

2021-09-27 16:32 UTC, anapaulagomes commented
Resolvido no #399. Obrigada a todos! :)

2021-09-27 16:32 UTC, closed without merging