Adiciona hash do commit aos itens coletados
DadosAbertosDeFeira/maria-quiteria pull request #421
Opened 2021-10-17 02:15 UTC by andressadotpy

- update tests to support hash_commit field
- added field to items and items validator
- modified base model DatasetMixin
- modified some helper functions inside management/commands
- modified parsers

2021-10-17 02:17 UTC, andressadotpy commented
@anapaulagomes como eram bastante arquivos pra atualizar, posso ter deixado passar algum lugar que devia ser atualizado, mas qualquer melhoria/esquecimento que for percebido no PR pode falar que ajeito rapidinho!

2021-10-18 16:50 UTC, andressadotpy commented
Oie @anapaulagomes! Fiz as mudanças, qualquer coisinha que precisar alterar estamos aí! muito obrigada

2021-11-03 06:25 UTC, anapaulagomes requested changes
Só precisamos fazer uma pequena modificação nos testes e estaremos prontas pra mergear!

2021-11-03 06:25 UTC, anapaulagomes commented on scraper/spiders/utils.py
> +    return os.environ.get("GIT_REV")
Boa! 👏🏽

2021-11-03 06:25 UTC, anapaulagomes commented on scraper/tests/test_utils.py
> +    os.environ["GIT_REV"] = "43fb0339d3758204cef63d3bc3ffadfda9b8dd3b"
Aqui estamos alterando diretamente o valor dessa variável no ambiente da pessoa que está rodando os testes, o que não é uma boa prática. É ideal que os testes rodem sem precisar modificar o ambiente. Para testes com variáveis de ambiente podemos usar o [`monkeypatch`](https://docs.pytest.org/en/6.2.x/monkeypatch.html#monkeypatching-environment-variables).

2021-11-03 06:28 UTC, anapaulagomes commented on web/datasets/migrations/0030_auto_20211018_1158.py
> +
Outra coisa: o build está falhando porque houve uma alteração nos models e nenhuma migration foi adicionada. A minha sugestão é: adicionar a migration, aplicar e depois voltar pra 0029, deletar a 30 e a 31 e gerar novamente. Assim esse PR vai adicionar apenas uma migration.

Quando tudo estiver pronto, não deixa de configurar a variável de ambiente com um hash de commit, rodar o `make crawl` e conferir no painel se salvou direitinho.

2023-01-29 18:56 UTC, anapaulagomes commented
Seria bom setarmos como nulo os registros que já existem e popular apenas os atuais (pra que não fique inconsistente).

2023-01-30 12:35 UTC, anapaulagomes commented
Fecha esse em favor da continuação no https://github.com/DadosAbertosDeFeira/maria-quiteria/pull/567.

2023-01-30 12:35 UTC, closed without merging