adiciona dateutil no projeto
DadosAbertosDeFeira/maria-quiteria pull request #587
Opened 2023-03-15 14:40 UTC by gabrielcjr

referente à issue https://github.com/DadosAbertosDeFeira/maria-quiteria/issues/410

2023-03-16 19:30 UTC, anapaulagomes requested changes
Obrigada pela contribuição, Gabriel! ✨  E muito bem-vindo!

Acho que começamos super bem. Uma parte importante que poderíamos substituir são os métodos `from_str_to_datetime` e `from_str_to_date`. Como tem testes pra eles, seria mais fácil de ver se algo foi quebrado. Depois de substituir, roda o crawler uma vez pra ver se continuamos capturando a data certinho (tem instruções no README mas qualquer dúvida é só chamar).

2023-05-02 20:47 UTC, anapaulagomes commented
Oi, @gabrielcjr! Precisando de ajuda por aqui?

2023-05-03 20:24 UTC, gabrielcjr commented
@anapaulagomes depois vou te chamar no Telegram pra ver uns detalhes deste pacote

2023-05-06 18:26 UTC, anapaulagomes commented on scraper/spiders/__init__.py
> +                picked_date = parse(self.start_from_date, yearfirst=True)
Acabei vendo na documentação que `yearfirst` seria o mais adequado pq no Brasil normalmente usamos o primeiro dígito como o dia (e não o ano). Nesse caso, o correto seria `dayfirst`.

2023-05-06 19:12 UTC, merged